"""add diagnosis to incidents

Revision ID: 5325313e81c9
Revises: a1f2b3c4d5e6
Create Date: 2026-08-13 00:38:42.568256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5325313e81c9'
down_revision = 'a1f2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('diagnosis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'diagnosis')
    # ### end Alembic commands ###