"""add incidents table

Revision ID: cfa440d22089
Revises: 8aab52e3789f
Create Date: 2026-08-15 18:32:53.635639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa440d22089'
down_revision = '8aab52e3789f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###