"""add status cate    op.add_column('incidents', sa.Column('status', sa.String(length=20), nullable=False))
gory resolved_at to incidents

Revision ID: e8c39c160f78
Revises: 5235a5a416a3
Create Date: 2026-08-10 01:01:14.924773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c39c160f78'
down_revision = '5235a5a416a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('incidents', sa.Column('status', sa.String(length=20), nullable=False, server_default='open'))
   op.add_column('incidents', sa.Column('category', sa.String(length=30), nullable=True))
   op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###