"""make incident_id nullable in reports

Revision ID: e92297c920b7
Revises: 950874e1e543
Create Date: 2026-08-18 00:09:42.911885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92297c920b7'
down_revision = '950874e1e543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###